let x = new Date()
console.log(x)
console.log(x.getDay())
console.log(x.getMonth())
console.log(x.getFullYear())
console.log(x.getTimezoneOffset())
console.log(x.getHours())
console.log(x.getMilliseconds())
console.log(x.getTime())

